### ISSUE TITLE
transfer to @bcomnes

### ISSUE THREAD

**Issue by ungoldman** [hypermodules/level-idx#20]
Ahoy @bcomnes 👋 

I only have two dependabot alerts left: this repo and hyperamp!

In an effort to reduce my daily maintenance emails, I am poking you once more about this particular repo.

From https://github.com/hypermodules/hypermodul.es/issues/81#issuecomment-1068536579 I believe this one is to be transferred to you -- want me to do that for you?

**Comment by bcomnes** [comment]
Oh yeah, I need to get around to doing that. If you don't mind, let's just leave it here till I have time to move it and fix anything that breaks because of it.

**Comment by ungoldman** [comment]
🙇
